remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"
locale: en-US

title: "Shine Zhang"
logo: "https://avatars.githubusercontent.com/u/723898?v=4"
description: "Do What Works, Do the Right Thing, and Be Kind!"

read_time: true
words_per_minute: 200

# Site Author
author:
  name: "Shine Zhang"
  location: "Texas, USA"
  picture: https://avatars.githubusercontent.com/u/723898?v=4
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/xinzweb/"

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/xinzweb
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

copyright: 2023 Shine Zhang

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-feed

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

markdown: kramdown

feed:
  path: atom.xml

# Page index
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy
tag_archive_path: "/tags/#"

# Front Matter Defaults
defaults:
  defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

